### ISSUE TITLE
When you use prevent on @submit event i throws an error saying e.preventDefault is not a function

### ISSUE THREAD

**Issue by sibalonat** [GustavoFenilli/formkit-addon-inertia#13]
So the scenario is this. When you actually have actions to true, and just use the form submission online, it works as a charm, but when you actually hook it to a function, It throws an error.

So the idea is as this example:
_I will try to solve it but help is also appreciated if you came across it earlier._

// methods
```
const submitRequest = (flds, node) => {
    useInertia(node).post(route('category.store'), flds)
}
```

and in formkit
```
                            <FormKit
                            type="form"
                            :actions="false"
                            @submit="submitRequest"
                            >
```

**Comment by sibalonat** [comment]
So yeah, i think so far there is a solution. At least I feel that this is working for me. On the submit button you hook another click event with method @click.prevent="submitbtn"
Make a reference to the form with ref="myform"
and then on this submitbtn add the following:
```
const submitbtn = () => {
    const node = myform.value.node
    node.submit()
}
```

if for you this looks verbose there is also a hook with an event on the node when you submit. But in all cases, it's a bit convoluted

**Comment by GustavoFenilli** [comment]
I would say the problem is with your button being a button maybe? make sure your button you're calling the function is a submit, or call it like you did with `node.submit`.

**Comment by sibalonat** [comment]
So my train of thought was. How to make inertia not reload as it does when you submit form. 
Because of the entire behavior, it looked quite strange. So I added a formkit button, but it was of type submit. So I'm not quite sure if it was related to that. As I see it right now, it looks more like spa behavior. It waits and then goes to the page after redirecting. So everything I was hoping for

**Comment by GustavoFenilli** [comment]
if you can create a reproduction I can take a look, but basically if you have something like this, it should work, as it will call the submit function properly.

```html
<FormKit type="form" @submit="submit" :actions="false">
  <FormKit type="submit" />
<FormKit />
```

**Comment by sibalonat** [comment]
So, in the end, Gustavo, you were right. It's less than 7 months since I'm using inertia and sometimes I mess up things. The reason it was fully reloading was that before when you did form submit in Inertia and you didn't specify the redirect it throw a type of error. So I figured only yesterday that, with the new inertia 1.0, the redirect is not required anymore. And it will reload the data but not fully reload. 

Your work is awesome man. Keep it up
