### ISSUE TITLE
Header response 409

### ISSUE THREAD

**Issue by Ragash** [GustavoFenilli/formkit-addon-inertia#14]
Hi Again, it seems there still a proble with dependencies with inertiajs.
i have a form which for testing i submit with inertia builtin 'useform' (trasforming the data with the form fields) and with the 'useInertia' from your package.

when using useInertia, it seems to not include the required "X-Inertia-Version:" into the header request, causing a 409 versioning error (and then reloading the whole page)

i suppose, since this is a behaviur related to inertia itself, it could depende on package version since inertia had a major update.
im on: "@inertiajs/vue3": "^1.0.2"

thanks for your time!

**Comment by aljabr** [comment]
i use next

but still require 
@inertiajs/inertia

my issue only on vite watch i got 409 error on submit the form

**Comment by GustavoFenilli** [comment]
Which version of inertia and this package are you using?

**Comment by aljabr** [comment]
"@inertiajs/vue3": "^1.0.7",
        "formkit-addon-inertia": "next",

**Comment by GustavoFenilli** [comment]
the next version shouldn't have anything requiring `@inertiajs/inergia` are you sure the node_modules have the correct version of `formkit-addon-inertia`? delete node_modules and the `lock` file and install the dependencies again.

**Comment by aljabr** [comment]
is it on ^1.0.0-beta.3?

i did multiple times :(

**Comment by aljabr** [comment]
<img width="1005" alt="Screenshot 2023-06-09 at 6 21 13 PM" src="https://github.com/GustavoFenilli/formkit-addon-inertia/assets/15986585/f9434b31-b431-4579-9c75-3a50211e3956">


i think the issue in dist/index.cjs.js

**Comment by aljabr** [comment]
https://www.npmjs.com/package/formkit-addon-inertia/v/1.0.0-beta.3?activeTab=code

**Comment by GustavoFenilli** [comment]
You are correct, didn't notice the build failed for beta.3, made some cleanups and all so now you can just install the `latest` and it will correctly work for `inertia: ^1.0.0`.

**Comment by aljabr** [comment]
it's working now 💯 ,

thank you!
