### ISSUE TITLE
Followed the composable way but component isn't rendered

### ISSUE THREAD

**Issue by merijnponzo** [GustavoFenilli/formkit-addon-inertia#6]
Hello,

I just copy pasted the composable way but it looks like the inputs arent rendered.

<img width="547" alt="Schermafbeelding 2022-11-24 om 09 37 01" src="https://user-images.githubusercontent.com/23075300/203733265-28f427fa-3102-4707-a376-605d45a8d521.png">

i'm using
```
 "@inertiajs/inertia": "^0.11.0",
        "@inertiajs/inertia-vue3": "^0.6.0",
        "@inertiajs/progress": "^0.2.7",
        "@vitejs/plugin-vue": "^3.0.0",
        "autoprefixer": "^10.4.2",
        "laravel-vite-plugin": "^0.5.0",
        "postcss": "^8.4.6",
        "vite": "^3.0.0",
        "vue": "^3.2.31"
    },
    "dependencies": {
        "@formkit/vue": "^1.0.0-beta.12",
        "@inertiajs/inertia": "^0.11.0",
        "@inertiajs/inertia-vue3": "^0.6.0",
        "formkit-addon-inertia": "^1.0.0",
        "postcss-nesting": "^10.1.10",
        "vue": "^3.2.36"
```

Are you sure that
```
<script setup>
import { useInertia } from "formkit-addon-inertia";
</script>

<template>
  <FormKit type="form" @submit="(fields, node) => useInertia(node).post('/user', fields)">
    <FormKit type="text" name="name" label="Name" />
    <FormKit type="email" name="email" label="E-mail" />
  </FormKit>
</template>
```
would load the formkit form? no registration on my app.js or anything?

thanks

**Comment by GustavoFenilli** [comment]
Did you follow the FormKit installation method? it seens to me that `<FormKit>` was not enabled globally by adding to the `vue.use(formkitPlugin, defaultConfig)` this addon only adds some functionality to the node, it does not make any changes to FormKit render capabilities.

**Comment by merijnponzo** [comment]
Hi Gustavo, i followed your  method 1 (adding formkit to a composable)

With the vue.use(formkitPlugin, defaultConfig) in my app.js createApp i couldn't get FormKit to work either.
So i hoped you addon was an all in one sollution to get FormKit to work.

Meanwhile i use some custom inputs from laravel breeze which work good as well, and is a bit lighter in filesize

**Comment by GustavoFenilli** [comment]
What was the problem with `vue.use`? this addon is only a integration between the two, so you need those two already configured with their respective installation methods.

**Comment by GustavoFenilli** [comment]
Will close for now, if you still have questions feel free to open it again or open a new issue.
