### ISSUE TITLE
errorBags, preserveScroll and more, Not working anymore

### ISSUE THREAD

**Issue by aljabr** [GustavoFenilli/formkit-addon-inertia#8]
Hi,

Everything was working great but after I updated vue the recentlySuccessful was not working.

And then I upgraded everything even this Addon to @next 

Now it return `TypeError: str.normalize is not a function`

When there an error and the preserveSroll not working anymore

I use  Laravel inertia

        "@inertiajs/vue3": "^1.0.0-beta.2",
        "formkit-addon-inertia": "next",
        "@formkit/vue": "^1.0.0-beta.12",

        "@vitejs/plugin-vue": "^4.0.0",

Thank you 🙏🏻

**Comment by aljabr** [comment]
i managed to resolve the error issue by passing this 

```
    onError: function (page, node) {
      this.errorBag ? node.setErrors(page[this.errorBag]) : node.setErrors(page)
    },
```
put the preserveScroll still 

this is the full snippet



`const submit = (fields, node) => {
  node.context.inertia.put(route('teams.update', props.team), fields, {
    errorBag: 'updateTeamName',
    preserveScroll: true,
    onError: function (page, node) {
      this.errorBag ? node.setErrors(page[this.errorBag]) : node.setErrors(page)
    },
  })
}`

**Comment by aljabr** [comment]
i found the issue with with the scroll
i have assigned a scroll-regions  to deferent element and its working fine without  @formkit-addon-inertia

https://inertiajs.com/scroll-management#scroll-regions 

and make the preserveScroll: false, will not do anything even if i make it as default "body"

**Comment by GustavoFenilli** [comment]
So do you think this is still a problem with `formkit-addon-inertia` or is something that is meant for the users use case only?

If so is there anything that the plugin can do to help make that work easily?

**Comment by aljabr** [comment]
i think  `formkit-addon-inertia` issue

this is what i use for inertia 

```
const form = useForm({
  name: props.team.name,
})

const updateTeamName = () => {
  form.put(route('teams.update', props.team), {
    errorBag: 'updateTeamName',
    preserveScroll: true,
  })
}
```
and now with `formkit-addon-inertia`

```
const updateTeamName = (fields, node) => {
  node.context.inertia.put(route('teams.update', props.team), fields, {
    errorBag: 'updateTeamName',
    preserveScroll: true,
    disableProgress: true,
    onError: function (page, node) {
      this.errorBag ? node.setErrors(page[this.errorBag]) : node.setErrors(page)
    },
  })
}
```

passing  `preserveScroll` will not work

recentlySuccessful will not work

processing will not work

this is the put from `inertia`
<img width="514" alt="Screenshot 2023-01-01 at 7 59 19 PM" src="https://user-images.githubusercontent.com/15986585/210178869-222d903f-e13a-4617-aa3a-65b44b9e1335.png">

this is the put from `formkit-addon-inertia`

<img width="739" alt="Screenshot 2023-01-01 at 7 58 42 PM" src="https://user-images.githubusercontent.com/15986585/210178916-9498112c-92ee-435e-a525-772d87e69731.png">

**Comment by aljabr** [comment]
this is with `inertia`

https://user-images.githubusercontent.com/15986585/210179312-780c6292-9b0d-43cd-ad3f-fe32137129af.mov

this is with `formkit-addon-inertia`

https://user-images.githubusercontent.com/15986585/210179315-ec500e12-3d43-492e-aeb6-50be0d478bf9.mov

as you can see the processing is not working and recentlySuccessful


Please note it was working when i was using formkit-inertify even i didn't had to pass onError

**Comment by GustavoFenilli** [comment]
I see so both preserveScroll and the error bags used to work with the oldest version, but it does not with the newest one?

so maybe it is something to do with the new `inertia: 1.0`, as you're using the `@next` version.

**Comment by GustavoFenilli** [comment]
also as a sidenote `disableProgress: true,` is not needed to be passed, it is in the example to show how to disable automatic features of the plugin, like adding the progress status to the context.

**Comment by aljabr** [comment]
yes everything on 

"formkit-addon-inertia": "^1.0.0-beta.1",
"@inertiajs/vue3": "^1.0.0-beta.2",

and preserveScroll did not work

**Comment by aljabr** [comment]
everything was working great before :)

then i did some updates and i saw you have renamed the plugin name and i changed,

thin the form did not work proprly
and after that I did upgrade to inertia to the beta so i did the same for this plugin

**Comment by aljabr** [comment]
when i was using 

```
        "@inertiajs/inertia": "^0.11.1",
        "@inertiajs/inertia-vue3": "^0.6.0",
        "@inertiajs/progress": "^0.2.7",
        "@inertiajs/server": "^0.1.0",

        "formkit-inertify": "^2.0.0-alpha.5",
```

the preserveScroll was working fine and I didnt had to pass onError but the only missing was  `recentlySuccessful` and  `processing`

**Comment by GustavoFenilli** [comment]
Okay I see the problem now, I took a look and .... I forgot to add the options that are passed back when changing to the new `useInertia`, so adding those back should fix both `preserveScroll` and `errorBag` problems.

as for `recentlySuccessful` and `processing` not sure on how they work, will take a look at these.

**Comment by aljabr** [comment]
I love you man  👍 

`recentlySuccessful` and `processing`

when i use Inertia to submit, it trigger something is missing here, sue i think useForm did it :)

```

const form = useForm({
  name: props.team.name,
})

const updateTeamName = () => {
  form.put(route('teams.update', props.team), {
    errorBag: 'updateTeamName',
    preserveScroll: true,
  })
}

```


https://user-images.githubusercontent.com/15986585/210182431-785238d2-bbd4-418f-baa4-dad355da454a.mov

**Comment by GustavoFenilli** [comment]
Oh I see so those are just reactive properties of useForm, it might be something worth adding to useInertia and the context.

**Comment by GustavoFenilli** [comment]
Ok this is now fixed at both `1.0.2` and `next` versions.

As for the case of the reactive values that useForm gives it would be worth opening another issue as a feature request instead.

**Comment by aljabr** [comment]
i think its not needed any more for the @next

https://next.inertiajs.com/upgrade-guide

<img width="853" alt="Screenshot 2023-01-02 at 12 22 27 AM" src="https://user-images.githubusercontent.com/15986585/210184942-3a19b254-a4b1-423d-91d6-62417152c77d.png">

**Comment by GustavoFenilli** [comment]
Did you remove the package json and updated? because the first line of the `@next` is `import { router } from '@inertiajs/vue3';`

**Comment by aljabr** [comment]
sorry for that i had to remove the node_module

can confirm it's working great one @next  👍 

Thank you so much.
